### ISSUE TITLE
1.8 / 1.12のサポートを改善できますか？

### ISSUE THREAD

**Issue by mocha666** [NekonekoNetwork/SlimeWorldManager#1]
このプロジェクトで1.8〜1.14の互換性が追加されていることをgithubで確認しました。1.8/ 1.12との互換性について何かできることはありますか？

**Comment by mc-nekoneko** [comment]
私達のサーバーでは、このプラグインを使用したプロジェクトをいくつか持っていますが、
現在は1.18.1での開発を行っており、現行の最新バージョンである1.18.1のみのサポートを目指しています。
`WorldUpgrader`についても互換性を保つ範囲は少なくとも、1.16~1.18.1の範囲で行われることを前提としています。
